[fix] change commands on main yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,8 +17,13 @@ jobs:
 
       - name: Run syntax check
         run: |
-          find . -name "*.php" -not -path "./vendor/*" -type f -exec sh -c 'php -l "{}" || echo "Error in file: {}"' \; 2>&1 | grep -v "No syntax errors detected" && exit 1
-
+          errors=$(find . -name "*.php" -not -path "./vendor/*" -type f -exec sh -c 'php -l "{}" || echo "Error in file: {}"' \; 2>&1 | grep -v "No syntax errors detected")
+          if [ -z "$errors" ]; then
+            echo "No syntax errors detected. Success!"
+          else
+            echo "$errors"
+            exit 1
+          fi
       - name: Pull code and deploy
         uses: appleboy/ssh-action@v0.1.10
         with:
